version: '3'
services:
  grobid:
    image: lfoppiano/grobid:0.7.1
    container_name: grobid
    ports:
      - "8070:8070"
    restart: unless-stopped

  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - grobid